-- Create the table--
CREATE TABLE bookmarkstable (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS identity,
	title TEXT UNIQUE NOT null,
	url VARCHAR unique not null,
	description text default 'Bookmark description',
	rating INTEGER NOT NULL CHECK(rating BETWEEN 0 AND 5)
);
--Insert a row --
INSERT INTO bookmarkstable
  (title, url, description, rating)
  VALUES (
    'Google',
    'http://google.com',
    'The google almighty',
    5
  );